#!/bin/bash 
alias gmx="gmx -nocopyright"
shopt -s expand_aliases
shopt expand_aliases
read -p "Please check your begining time and ending time,and other settings" yes 
read -p "Please input the name" name
type=25
AA_amounts=36
while [ "$type" -lt $AA_amounts ]; do
  {
	  VDW_energy=`awk 'NR==1 {print $3-$2-$1}' all.dat`
    Coulomb_energy=`awk 'NR>=2 {C_plus+=$3; C_g1+=$1; C_g2+=$2} END{print (C_plus-C_g1-C_g2)}' all.dat` 
    echo "$type VDW_energy $VDW_energy Coulomb_energy $Coulomb_energy" >> all.date
}

